/**
 * The auto-close rail's decision core, mirrored from the executors' shared
 * evaluator (`poly_track/copy_trade/auto_close.py`, upstream #363/#364).
 *
 * Both bots run the identical rail, so both walkthroughs read it out of this
 * one module — and the parity suite pins it against fixtures generated by the
 * Python evaluator itself, so the page can never describe a close the running
 * system would not make.
 */

import { platformFeeUsdc } from "./market-math";

/** The three figures the rail reads off an executor's close plan. */
export interface ClosePlan {
	readonly realizedPnlUsdc: number;
	readonly costUsdc: number;
	readonly entryFeeUsdc: number;
}

/** Whole-percent thresholds (`30` = 30 %); `0` stands that side down. */
export interface AutoCloseThresholds {
	readonly lossPct: number;
	readonly profitPct: number;
}

/** Consecutive breached ticks in one direction — per-position state. */
export interface BreachStreak {
	readonly direction: AutoCloseDecision | null;
	readonly ticks: number;
}

export type AutoCloseDecision = "none" | "stop_loss" | "take_profit";

export const FRESH_STREAK: BreachStreak = { direction: null, ticks: 0 };

/** How many consecutive breached ticks a side needs before it fires. */
const DEBOUNCE_TICKS = 2;

export interface AutoCloseEvaluation {
	readonly decision: AutoCloseDecision;
	readonly streak: BreachStreak;
	readonly netPct: number;
}

/**
 * What a full close now would realize, as a percent of what was paid. The
 * realized figure is already net of both fees and the basis includes the entry
 * fee — the operator's question is "how much of what I put in would I get
 * back". Nothing paid means no percent of it can move.
 */
export function netRealizablePct(plan: ClosePlan): number {
	const basis = plan.costUsdc + plan.entryFeeUsdc;
	if (basis <= 0) return 0;
	return (plan.realizedPnlUsdc / basis) * 100;
}

/**
 * One tick of the rail for one position. The two sides are mutually exclusive
 * by construction: an enabled loss side needs a strictly negative reading and
 * an enabled profit side a strictly positive one.
 */
export function evaluateAutoClose(
	plan: ClosePlan,
	{ thresholds, streak = FRESH_STREAK }: { thresholds: AutoCloseThresholds; streak?: BreachStreak },
): AutoCloseEvaluation {
	const netPct = netRealizablePct(plan);

	let direction: AutoCloseDecision;
	if (thresholds.lossPct > 0 && netPct <= -thresholds.lossPct) {
		direction = "stop_loss";
	} else if (thresholds.profitPct > 0 && netPct >= thresholds.profitPct) {
		direction = "take_profit";
	} else {
		return { decision: "none", streak: FRESH_STREAK, netPct };
	}

	const ticks = streak.direction === direction ? streak.ticks + 1 : 1;
	return {
		decision: ticks >= DEBOUNCE_TICKS ? direction : "none",
		streak: { direction, ticks },
		netPct,
	};
}

// The path shapes stay module-private, the way both simulators' verdict shapes
// do: every consumer reads them off `runAutoClosePath`'s inferred return type,
// so exporting them would widen the interface for nobody.

/** One tick as the walkthrough prints it. `null` figures are an unread book. */
interface AutoCloseTick {
	/** 1-based, the way the reader counts them. */
	readonly tick: number;
	/** False when the book had no bid to price a close against. */
	readonly quotable: boolean;
	readonly netPct: number | null;
	readonly decision: AutoCloseDecision;
	/** Consecutive breached ticks standing after this one. */
	readonly streakTicks: number;
}

interface AutoClosePath {
	readonly ticks: readonly AutoCloseTick[];
	/** The 1-based tick the position closed on, or `null` if it never did. */
	readonly closeTick: number | null;
	readonly decision: AutoCloseDecision;
	/** The percent the close booked, or the last reading on a path that held. */
	readonly netPct: number | null;
}

/**
 * The rail walked over a whole sequence of readings — what the reader watches
 * tick by tick. A `null` reading is an unreadable or bid-less book: the strict
 * quote policy skips that position for the tick and resets its breach streak,
 * because a remembered mark is not a price anything can be sold at.
 *
 * Reading stops at the close. A closed position has nothing left to quote, and
 * printing ticks past it would invite the reader to believe the rail kept
 * watching money that was already back in the account.
 */
export function runAutoClosePath(
	readings: readonly (ClosePlan | null)[],
	thresholds: AutoCloseThresholds,
): AutoClosePath {
	const ticks: AutoCloseTick[] = [];
	let streak = FRESH_STREAK;
	let lastPct: number | null = null;

	for (const [index, reading] of readings.entries()) {
		const tick = index + 1;
		if (reading === null) {
			streak = FRESH_STREAK;
			ticks.push({ tick, quotable: false, netPct: null, decision: "none", streakTicks: 0 });
			continue;
		}

		const evaluation = evaluateAutoClose(reading, { thresholds, streak });
		streak = evaluation.streak;
		lastPct = evaluation.netPct;
		ticks.push({
			tick,
			quotable: true,
			netPct: evaluation.netPct,
			decision: evaluation.decision,
			streakTicks: evaluation.streak.ticks,
		});

		if (evaluation.decision !== "none") {
			return { ticks, closeTick: tick, decision: evaluation.decision, netPct: evaluation.netPct };
		}
	}

	return { ticks, closeTick: null, decision: "none", netPct: lastPct };
}

/**
 * What closing this position at this bid would realize, priced the way each
 * executor's operator-close primitive prices it: proceeds at the best bid, the
 * venue's per-share fee off both ends, basis the ticket plus its entry fee.
 *
 * The rail itself never sees prices — it reads the three figures this returns.
 * Keeping the derivation here rather than inside the evaluator is what lets the
 * parity fixtures pin the decision without pinning the venue's arithmetic.
 */
export function planAtBid({
	shares,
	entryPrice,
	bid,
}: {
	shares: number;
	entryPrice: number;
	bid: number;
}): ClosePlan {
	const costUsdc = shares * entryPrice;
	const entryFeeUsdc = platformFeeUsdc(shares, entryPrice);
	const exitFeeUsdc = platformFeeUsdc(shares, bid);
	return {
		realizedPnlUsdc: shares * bid - costUsdc - entryFeeUsdc - exitFeeUsdc,
		costUsdc,
		entryFeeUsdc,
	};
}

/**
 * One made-up position and the book it is quoted against, tick by tick. Every
 * figure is invented for the walkthrough — never a real position, a real market
 * or a real balance (see the disclosure policy on the methodology page).
 */
export interface AutoCloseScenario {
	readonly id: string;
	/** What the ticket cost, so the reader can do the arithmetic themselves. */
	readonly sizeUsdc: number;
	readonly entryPrice: number;
	/** Best bid at each tick; `null` is a book with nothing resting on it. */
	readonly bids: readonly (number | null)[];
}

/**
 * Four price paths, one per thing the rail can do: stop out, take profit,
 * whipsaw across a threshold without ever firing, and lose a close to an
 * unreadable book. The rail polls about once a minute, so a tick is a minute.
 *
 * `as const satisfies` keeps the literal tuple type, so `AUTO_CLOSE_SCENARIOS[0]`
 * is a scenario rather than possibly-undefined and the SSR paint needs no guard.
 */
export const AUTO_CLOSE_SCENARIOS = [
	{
		id: "drifts-down",
		sizeUsdc: 5,
		entryPrice: 0.4,
		bids: [0.38, 0.34, 0.3, 0.28, 0.26],
	},
	{
		id: "runs-up",
		sizeUsdc: 5,
		entryPrice: 0.4,
		bids: [0.48, 0.56, 0.62, 0.66, 0.7],
	},
	{
		// Across the line and back. One breached tick is never a close, which is
		// the whole point of asking for two.
		id: "whipsaw",
		sizeUsdc: 5,
		entryPrice: 0.4,
		bids: [0.3, 0.38, 0.29, 0.42, 0.34],
	},
	{
		// The strict quote policy, dramatized: without the gap at tick two this
		// position would have stopped out at tick three.
		id: "book-gap",
		sizeUsdc: 5,
		entryPrice: 0.4,
		bids: [0.3, null, 0.29, 0.36, 0.34],
	},
] as const satisfies readonly AutoCloseScenario[];

/** The shares a scenario's ticket bought at its entry price. */
function scenarioShares(scenario: AutoCloseScenario): number {
	return scenario.entryPrice > 0 ? scenario.sizeUsdc / scenario.entryPrice : 0;
}

/** A scenario's book, priced into the readings the rail actually judges. */
export function autoCloseReadings(scenario: AutoCloseScenario): (ClosePlan | null)[] {
	const shares = scenarioShares(scenario);
	return scenario.bids.map((bid) =>
		bid === null ? null : planAtBid({ shares, entryPrice: scenario.entryPrice, bid }),
	);
}
